name: Build and Release Latest

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete Existing Latest Release
        run: |
          gh release delete "latest" --yes || echo "No previous 'latest' release to delete."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Existing Latest Tag
        run: |
          git tag -d "latest" || echo "No local 'latest' tag to delete."
          git push origin --delete "latest" || echo "No remote 'latest' tag to delete."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create New Latest Tag
        run: |
          git tag latest
          git push origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP archive
        run: |
          zip -r zoro.zip . -x ".git*" -x ".github/*"

      - name: Create New Latest Release with ZIP
        run: |
          gh release create "latest" \
            "zoro.zip" \
            --title "latest" \
            --notes "Automatically built from the latest commit. Download the 'zoro.zip' file below to run the project." \
            --target ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}